openapi: 3.0.1
info:
  title: Master service
  description: Master service API
  version: "0.0"
servers:
- url: http://localhost:8101/
  description: master service local
- url: http://foo
  description: master service
tags:
- name: Master Service
  description: Master Service API
paths:
  /:
    get:
      tags:
        - Route Controller
      summary: Index.
      description: Index.
      operationId: indexGet1
      parameters: []
      responses:
        "200":
          description: the http response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
  /master:
    get:
      tags:
        - Master Service
      summary: Load Type
      description: Load Type
      operationId: indexGet2
      parameters: []
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
