openapi: 3.0.1
info:
  title: Master service
  description: Master service API
  version: "0.0"
servers:
- url: http://localhost:8101/
  description: master service local
- url: http://foo
  description: master service
tags:
- name: Master Service
  description: Master Service API
paths:
  /:
    get:
      tags:
        - Route Controller
      summary: Index.
      description: Index.
      operationId: indexGet1
      parameters: []
      responses:
        "200":
          description: the http response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
  /master:
    get:
      tags:
        - Master Bigger
      summary: Load Type
      description: Load Type
      operationId: indexGet2
      parameters: []
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    AccountDTO:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        accountStatus:
          type: integer
          format: int32
        passwordExpirationDate:
          type: string
          format: date-time
        email:
          type: string
        updateDate:
          type: string
          format: date-time
        deleteFlag:
          type: boolean
        telephoneNumber:
          type: string
        accountType:
          type: integer
          format: int32
        changePasswordToken:
          type: string
        changePasswordExpirationDate:
          type: string
          format: date-time
        verifiedFlag:
          type: boolean
        customerCode:
          type: string
        newPass:
          type: string
        oldPass:
          type: string
        confirmNewPass:
          type: string
        socialToken:
          type: string
        accountSource:
          type: integer
          format: int32
        customerId:
          type: integer
          format: int64
        rmsToken:
          $ref: '#/components/schemas/JwtAuthenticationResponse'
        uuid:
          type: string
          format: uuid
        brand:
          type: string