openapi: 3.0.1
info:
  title: micronaut-openapi-example
  version: "0.0"
paths:
  /Example1:
    get:
      tags:
      - Example 1
  /Example2:
    get:
      tags:
        - Example 1
components:
  schemas:
    AccessibleObject:
      type: object
      properties:
        accessible:
          type: boolean
          deprecated: true
        annotations:
          type: array
          items:
            $ref: '#/components/schemas/Annotation'
        declaredAnnotations:
          type: array
          items:
            $ref: '#/components/schemas/Annotation'


