micronaut:
  application:
    name: bookService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8101
netty:
  default:
    allocator:
      max-order: 3
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
